//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet2
    {
        public int SepetId { get; set; }
        public int SepetUrunId { get; set; }
        public int SepetUyeId { get; set; }
        public int SepetOnay { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
